### ISSUE TITLE
Idea: Create a docs directory

### ISSUE THREAD

**Issue by jtopjian** [terraform-lxd/terraform-provider-lxd#111]
I'm going to have some time to work on some outstanding issues. If I'm lucky, some of that work is going to be the creation of two new resources: a dedicated container file resource and there's a storage attach resource I said I would create a long time ago.

New resources means new docs and that got me thinking about our current README file.

Does anyone have thoughts or objections to creating a `docs` directory where each resource could have a dedicated `.md` file?

/cc @mjrider @sl1pm4t

**Comment by mjrider** [comment]
i think that is a very good idea

**Comment by sl1pm4t** [comment]
We could also add an `examples/<resource>` subdirs with example TF configs.
