### ISSUE TITLE
Unable to create LVM storage pool

### ISSUE THREAD

**Issue by antoinesax** [terraform-lxd/terraform-provider-lxd#161]
Hi,

I'm using LXD 3.12 and terraform lxd provider v1.1.3. I have 2 nodes running LXD in clustering mode and I want to define a new storage pool but it doesn't work because of 'node-specific' variables like `source`.

My resource definition with `source` configuration:
```
resource "lxd_storage_pool" "basic-pool" {
  name = "basic-pool"
  driver = "lvm"

  config {
    source = "vg-host"
  }
}
```

I got the following error:
`* lxd_storage_pool.basic-pool: Config key `source` is node-specific`

When removing the `source` field, I got the following error:
`lxd_storage_pool.basic-pool: Pool not pending on any node (use --target <node> first)`
But I don't want to declare the pool by hand on each node before, and I'm not able to specify the `target` in terraform resource (I tried with `remote` attribute without success).

Does anyone can help me?
Thanks

**Comment by jtopjian** [comment]
This has been implemented in #224 and will be available in the next release.
