### ISSUE TITLE
LXD cluster

### ISSUE THREAD

**Issue by ojan** [terraform-lxd/terraform-provider-lxd#164]
I've tried the plugin on an LXD standalone and it works fine. Now, i try to create a network on a lxd cluster with no luck.

It seems that the necessary `target` parameter for lxd is not in the plugin like show in the below output

```
Error: Network not pending on any node (use --target <node> first)

  on network/main.tf line 28, in resource "lxd_network" "ovsbr0":
  28: resource "lxd_network" "ovsbr0" {
```

I get the same error on the command line

```
lxc network create ovsbr2
Error: Network not pending on any node (use --target <node> first)
```

This one works

```
 lxc network create ovsbr2 --target lxd1
```

Is it possible to add this parameter ?
Thanks

**Comment by jtopjian** [comment]
This should be implemented in #222 and will be available in the next release. Though please let me know if anyone has any issues.
