### ISSUE TITLE
[FEATURE REQUEST] lxd_snapshot ability to restore from a snapshot

### ISSUE THREAD

**Issue by thepenguinthatwants** [terraform-lxd/terraform-provider-lxd#190]
Hi guys!

I've noticed that lxd_snapshot is able to create new snapshots but unable to revert images into the snapshot state.

Is it possible to make it that if a snapshot exists with the same name then it will revert image to the snapshot state? Or have a argument to make it revert back into the stage of the snapshot if exists?

**Comment by jtopjian** [comment]
@thepenguinthatwants Can you provide an example of how this would be used?

Generally speaking, Terraform manages the full lifecycle of resources. So situations where something already exists are usually not good candidates to be done by Terraform.

**Comment by thepenguinthatwants** [comment]
Hi!

I was thinking about that if it uses an lxc image that already exists with snapshots it could choose and use that snapshot. Like easily swapping from different snapshots that are in different states.

**Comment by jtopjian** [comment]
Ah, I see. You're right in that this provider currently provide any sort of "restore" support with snapshots. We'll have to think about a good way to integrate it.
