### ISSUE TITLE
Unable to use "lxd_network" with existing bridge (unmanaged)

### ISSUE THREAD

**Issue by otopetrik** [terraform-lxd/terraform-provider-lxd#201]
It looks like there is no *clean* way to use existing bridge - like virbr0 provided by libvirt (or similar bridge configured using systemd-networkd).
The bridge is already automatically available to lxd, listed in `lxc network show virtbr0` (with `managed:false`).

- lxd_network create fails (`Error: The network already exists`)
- `terraform import lxd_network` does not work (`Error: resource lxd_network doesn't support import`)
- there is no corresponding data source (e.g. like [data source](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file)
to [resource](https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file)

Not sure what is the correct solution. But it would be nice to catch errors like "mistyped bridge name in terraform file" or "unmanaged bridge not present" *before* container creation fails.

- a) Add `managed` argument to resource `lxd_network`

Default to `true`. If set to `false`, then on create only verify that lxd network exists and is unmanaged, on destroy do nothing.
The `config` argument should be required only for managed networks (and forbidden for unmanaged).

This should catch errors before container creation - at `lxd_network` resource creation time.

- b) Data source `lxd_network` (e.g. read-only `data "lxd_network"`)

This would probably catch errors even sooner (at the `terraform plan` stage ?).

**Comment by jtopjian** [comment]
I've implemented basic support for importing networks in #226. 

This will be available in the next release and it should resolve this issue for you. If you're still having problems, please let me know.
