### ISSUE TITLE
Error: Failed to install provider

### ISSUE THREAD

**Issue by brandonros** [terraform-lxd/terraform-provider-lxd#203]
```
$ uname -a
Linux debian 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
```

```
$ terraform version
Terraform v0.13.2
```

```
mkdir -p ~/.terraform.d/plugins
cd ~/.terraform.d/plugins
wget "https://github.com/sl1pm4t/terraform-provider-lxd/releases/download/v1.3.0/terraform-provider-lxd_v1.3.0_linux_amd64.zip"
unzip terraform-provider-lxd_v1.3.0_linux_amd64.zip 
rm *.zip
```

```
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/lxd...

Error: Failed to install provider

Error while installing hashicorp/lxd: provider registry registry.terraform.io
does not have a provider named registry.terraform.io/hashicorp/lxd
```

**Comment by brandonros** [comment]
had to add

```
terraform {
  required_providers {
    lxd = {
      source  = "arren-ru/lxd"
      version = "1.3.1"
    }
  }
}
```

**Comment by jtopjian** [comment]
That's not this provider... someone appears to have forked this provider and published it to the registry.

@sl1pm4t Can we look at getting this published to the registry? We should also contact HashiCorp about the other one being published, too.

**Comment by jtopjian** [comment]
The following workaround works for now:

```bash
$ mkdir -p ~/.terraform.d/plugins/registry.terraform.io/sl1pm4t/lxd/1.3.0/linux_amd64
$ cd ~/.terraform.d/plugins/registry.terraform.io/sl1pm4t/lxd/1.3.0/linux_amd64
$ wget https://github.com/sl1pm4t/terraform-provider-lxd/releases/download/v1.3.0/terraform-provider-lxd_v1.3.0_linux_amd64.zip
$ unzip terraform-provider-lxd_v1.3.0_linux_amd64.zip 
$ rm *.zip
```

And then in the `.tf` file:

```hcl
terraform {
  required_providers {
    lxd = {
      source = "sl1pm4t/lxd"
    }
  }
}
```

**Comment by brandonros** [comment]
not sure if you wanna document this on the README for future users? :D

**Comment by jtopjian** [comment]
Yeah, once we get this published to the registry I'll update the README accordingly. 😄

**Comment by arren-ru** [comment]
@brandonros that binary was published by me when I found that new versions of terraform required repository and I didn't know about workaround as was suggested by @jtopjian. Anyway that provider was built on top of master branch forked from this repo. There is no custom changes.
When Joe will release his provider in his repo namespace, I recommend to switch and use it instead of mine.

**Comment by jtopjian** [comment]
@arren-ru All good - thanks!

@sl1pm4t is on vacation at the moment, but I hope to be able to get this published to the registry soon.

**Comment by arren-ru** [comment]
Trying to keep it fresh in terraform registry https://registry.terraform.io/providers/arren-ru/lxd/1.4.0

**Comment by jtopjian** [comment]
Looks like we're good to go: https://registry.terraform.io/providers/terraform-lxd/lxd

The README has been updated with basic instructions: https://github.com/terraform-lxd/terraform-provider-lxd

Please let me know if anyone has any questions or runs into any problems. Thank you for your patience!
