### ISSUE TITLE
Can't create macvlan or other type of networks with lxd_network

### ISSUE THREAD

**Issue by arren-ru** [terraform-lxd/terraform-provider-lxd#214]
Seems to be lxd_network does not support to set type of network
Using this resource definition:
```hcl
resource "lxd_network" "macvlan" {
  name   = "macvlan"
  config = {
    "parent" = "hp1"
  }
}
```
I've got an error:
```text
Terraform will perform the following actions:
  # lxd_network.macvlan will be created
  + resource "lxd_network" "macvlan" {
      + config  = {
          + "parent" = "hp1"
        }
      + id      = (known after apply)
      + managed = (known after apply)
      + name    = "macvlan"
      + type    = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
…
lxd_network.macvlan: Creating...

Error: Invalid option for network "macvlan" option "parent"

  on main.tf line 24, in resource "lxd_network" "macvlan":
  24: resource "lxd_network" "macvlan" {
```

Seems to be there is need to rework the lxd_network resource.

**Comment by jtopjian** [comment]
@arren-ru The config details are passed directly to LXD. The error you're seeing:

```
Error: Invalid option for network "macvlan" option "parent"
```

Is coming from the LXD service itself, not Terraform. I recommend walking through the steps for creating a macvlan-type network using the command line, then viewing the configuration details (`lxc network show <name>`) and seeing if there are any other configuration details missing.

One possibility is that the `parent` actually goes on the NIC device rather than the network?

**Comment by jgraichen** [comment]
I think the problem might be that the `type` attribute of `lxd_network` cannot be set but only computed. LXD will therefore always trying to create a bridge network that does not support the `parent` option.

It might need a change to allow something like this:

```hcl
resource "lxd_network" "net1" {
  name = "net1"
  type = "macvlan"
  config {
    "parent" = "eth0"
  }
}
```

This would be similar to `lxc network create <name> --type=macvlan [options...]` as seen [here](https://lxd.readthedocs.io/en/latest/networks/).

**Comment by jtopjian** [comment]
You're right. This should be easy to do - I think the version of the LXD client API that we have pinned in `go.mod` will support this. I'll look at modifying this argument once the other PRs are merged.

**Comment by jtopjian** [comment]
This should be working in #220, but please let me know if you're still having problems.
