### ISSUE TITLE
arm64 add to releases 

### ISSUE THREAD

**Issue by necrose99** [terraform-lxd/terraform-provider-lxd#217]
[**linux/arm64** ](https://raw.githubusercontent.com/sl1pm4t/terraform-provider-lxd/master/Makefile)

**https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_arm64.zip**

**Comment by jtopjian** [comment]
This has been included in the latest release: https://github.com/terraform-lxd/terraform-provider-lxd/releases/tag/v1.4.1
