### ISSUE TITLE
How to use centos image? I could get ubuntu work but not centos

### ISSUE THREAD

**Issue by thepenguinthatwants** [terraform-lxd/terraform-provider-lxd#231]
Hi guys,
I've being usually using it like 
`   image = "ubuntu:18.04"`
And it works

```
resource "lxd_container" "machinery" {
   name  = "machinery"
   image = "centos/7"
   ephemeral = false
   profiles = ["default"]
   config = {
     "boot.autostart" = false
   }
   device {
     name = "eth0"
     type = "nic"
     properties = {
       nictype        = "bridged"
       parent         = "lxdbr0"
       "ipv4.address" = "10.41.124.203"
     }
   }
 }

```

I tried many different ways to write centos but it just says image not found.
When running manually in terminal
`lxc launch images:centos/7 test`
worked

Any clue why its like this?

**Comment by mbwe** [comment]
You should change the following line from: 

image = "centos/7"

to

image = "images/centos/7"

You can only reference Ubuntu images directly.
