### ISSUE TITLE
VM support

### ISSUE THREAD

**Issue by dsx** [terraform-lxd/terraform-provider-lxd#249]
LXD v4.x has support for [VMs](https://discuss.linuxcontainers.org/t/running-virtual-machines-with-lxd-4-0/7519). Are there plans to add support for VMs to the LXD Terraform provider?

**Comment by jtopjian** [comment]
This should already be supported via the `type` parameter in `lxd_container`: https://github.com/terraform-lxd/terraform-provider-lxd/blob/master/docs/resources/container.md

**Comment by matjazp** [comment]
I'm using it to deploy VMs and it works as expected.

**Comment by dsx** [comment]
Oh, my bad! Thanks a lot @matjazp and @jtopjian!
