### ISSUE TITLE
Cloud Init Support

### ISSUE THREAD

**Issue by WarpWing** [terraform-lxd/terraform-provider-lxd#251]
Hi all!

Is there a way to reference a cloud-init file when creating an lxd container? I couldn't find it in the documentation.

**Comment by rhass** [comment]
You might be able to do something like:

```hcl
data "template_file" "cloudinit_user_data" {
  template = file("./templates/cloud_init_user_data.tpl")

  vars = {
    foo = file(var.myfile)
  }
}

resource "lxd_profile" "my_cloudinit" {
  name = "my-cloudinit"

  config = {
    "user.user-data" = data.template_file.cloudinit_user_data.rendered
  }
}
```

Once you have that, you can use that profile in addition to any other profiles you may have.

**Comment by WarpWing** [comment]
It works! Thanks for your help!
