### ISSUE TITLE
Request to add Apple M1 support

### ISSUE THREAD

**Issue by billgrant** [terraform-lxd/terraform-provider-lxd#253]
Hello,

Is there plans or would it be possible to add "darwin_arm64" support to the provider?

`Initializing Terraform Cloud...

Initializing provider plugins...
- Finding latest version of terraform-lxd/lxd...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/terraform-lxd/lxd v1.7.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions
│ of this provider may have different platforms supported`

**Comment by matjazp** [comment]
I've built it manually (Go 1.17 on MacBook Pro M1), and it works (at least for my use cases).

@jtopjian I think we could get darwin/arm64 version automatically with just upgrading Go to at least 1.16? Goreleaser should automatically build for darwin/arm64 if go version is >=1.16. This is in CICD logs:

>       • DEPRECATED: skipped darwin/arm64 build on Go < 1.16 for compatibility, check https://goreleaser.com/deprecations/#builds-for-darwinarm64 for more info.

**Comment by jtopjian** [comment]
Sorry for the delay - I'm looking into this now.

**Comment by jtopjian** [comment]
I've just released version 1.7.1 which looks to have `darwin/arm64` support. Can someone confirm that it's working?

**Comment by billgrant** [comment]
> I've just released version 1.7.1 which looks to have `darwin/arm64` support. Can someone confirm that it's working?

It works for me on an M1 
`Initializing provider plugins...
- Finding latest version of terraform-lxd/lxd...
- Installing terraform-lxd/lxd v1.7.1...
- Installed terraform-lxd/lxd v1.7.1 (self-signed, key ID 62BC1162214B5D1E)`

**Comment by jtopjian** [comment]
Awesome - thanks so much for testing!

I'm going to close this issue but please let me know if you have any problems.
