### ISSUE TITLE
Config keys not seen and continously replaced.

### ISSUE THREAD

**Issue by Eihrister** [terraform-lxd/terraform-provider-lxd#258]
Hello!

Since I use static MAC-addresses when building up and tearing down the same containers over and over, I would like to set the hwaddr of the network interface through Terraform. It works, but the lxd module doesn't seem to see that it's already set when I "plan".

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.11.0
+ provider registry.terraform.io/hetznercloud/hcloud v1.33.2
+ provider registry.terraform.io/kreuzwerker/docker v2.16.0
+ provider registry.terraform.io/terraform-lxd/lxd v1.7.1
+ provider registry.terraform.io/vultr/vultr v2.10.1
```

Resource config:

```
resource "lxd_container" "control1" {
  name      = "control1"
  config    = { "volatile.eth0.hwaddr" = "00:16:3e:5b:66:61" }

  type      = "virtual-machine"
  image     = "images:ubuntu/22.04/cloud/amd64"
  profiles  = ["kubernetes", "controller"]

  ephemeral = false
}
```

And this works, however, on consequent "plan" or "apply" runs:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # lxd_container.control1 will be updated in-place
  ~ resource "lxd_container" "control1" {
      ~ config           = {
          + "volatile.eth0.hwaddr" = "00:16:3e:5b:66:61"
        }
        id               = "control1"
        name             = "control1"
        # (9 unchanged attributes hidden)
    }
```

This shouldn't pop up? Or am I doing something wrong? Relatively new to Terraform!

Daniël

**Comment by jtopjian** [comment]
@Eihrister The "volatile" keys are used internally by LXD and they can't be set by a user. More information about that can be found here: https://linuxcontainers.org/lxd/docs/master/instances/

If you want to specify a MAC address on the interface, you'll most likely need to declare an `eth0` device within the container resource and then set the `hwaddr`. This example might help: https://github.com/terraform-lxd/terraform-provider-lxd/blob/master/lxd/resource_lxd_container_test.go#L1067-L1087

**Comment by Eihrister** [comment]
Hi @jtopjian!

Thank you for your answer; I used to set this volatile key through the CLI before, just as a one-off at first and somehow stuck with it.. not sure why. This is, of course, a much healthier way :)

This works fine, thanks again!
