### ISSUE TITLE
Create images from local files

### ISSUE THREAD

**Issue by Hybrid512** [terraform-lxd/terraform-provider-lxd#262]
Hi,

I'd like to create images directly with Terraform based on local qcow2 images (this is for VM provisionning).
I can easily create a new image with the lxc cli and then spawn some VMs with Terraform but I'd like to do the whole stuff directly with Terraform.
To make it clear, I'd like to do the equivalent of :

`lxc image import metadata.tar.xz jammy-server-cloudimg-amd64.img.tar.xz --alias ubuntu-jammy-22.04`

but with Terraform.
Is it possible ?
Can you provide an example because I'm quite confused with the documentation regarding the "images" part.

Best regards

**Comment by antoonhuiskens** [comment]
I'd use hashicopr packer to handle that. 

With recent versions of packer be sure to include:
```
packer {
  required_plugins {
    lxd = {
      version = ">= 1.0.1"
      source  = "github.com/hashicorp/lxd"
    }
  }
}
```

From there you could hook this into terraform with (presumably) null_resources and provisioners to trigger terraform driven packer builds.

**Comment by adamcstephens** [comment]
This LXD provider currently has no capability to import an image. The only support right now is for ensuring an image is cached from another remote (either image server or LXD server).

If you're looking to build and then import your own images, you may want to automate that outside Terraform. I'm also not even sure this is a good fit for pure terraform given that it would tightly couple the terraform code to large files.

I'm going to close this given the age, but if someone wants to pursue an implementation I'd be happy to discuss.
