### ISSUE TITLE
How to add a second volume as a secondary block device inside VM ?

### ISSUE THREAD

**Issue by Hybrid512** [terraform-lxd/terraform-provider-lxd#263]
Hi,

I'm trying to add a secondary volume as a block device inside my VM but I can't find a way to do it.
My only working attempts mounts a volume as a 9p mounted share which is not what I want.
Is there a way to just add a secondary block device ?
How ?

**Comment by gboutry** [comment]
Hi @Hybrid512,

The capability to create block volumes was added recently but is not released yet.
When it is released, you will need to create a volume with `content_type = "block"`, and attach it to your VM.

Example:
```tf
resource "lxd_volume" "my-volume" {
  name         = "vol"
  pool         = "default"
  type         = "custom"
  content_type = "block"
  config = {
    size = "10GiB"
  }
}

resource "lxd_container" "my-container" {
...
  device {
    name = lxd_volume.my-volume.name
    type = "disk"
    properties = {
      pool   = "default"
      source = lxd_volume.my-volume.name
    }
  }
}

**Comment by adamcstephens** [comment]
v1.10.0 has been released with this enhancement.
