### ISSUE TITLE
Error waiting for container network information

### ISSUE THREAD

**Issue by mkgvt** [terraform-lxd/terraform-provider-lxd#269]
I am having trouble getting a [simple](https://github.com/terraform-lxd/terraform-provider-lxd/files/9708011/issue.tf.txt) LXD container to work. It consistently fails after about 3m20s of "still creating...". The  [transrcript](https://github.com/terraform-lxd/terraform-provider-lxd/files/9708005/tflxd-error.txt) suggests the container times out after 3m0s waiting on the IPv4 network. Explicitly checking the resource shows the network has been created yet the container, which ends up running, doesn't have an IPv4 address. I don't see anything obvious with my LXD [configuration](https://github.com/terraform-lxd/terraform-provider-lxd/files/9708133/lxc.info.txt). I'm at a loss of what is going wrong. Perhaps something is wrong with the TF file. Or it could be an bug in the provider.

Note: perhaps the provider should implement [timeouts](https://www.terraform.io/plugin/sdkv2/resources/retries-and-customizable-timeouts) for some things so that additional time can be given for the network to respond.

**Comment by adamcstephens** [comment]
In my experience it is an LXD network configuration or host network/firewall configuration that would cause this. For example I've had a firewall blocking the DHCP packets destined for the dnsmasq instance, and the instance never gets an IP.

Closing. If you still feel this is an issue, please reply or reopen.
