### ISSUE TITLE
Unable to create a block custom volume

### ISSUE THREAD

**Issue by Nuttymoon** [terraform-lxd/terraform-provider-lxd#277]
LXD supports 2 types of ["custom" storage volumes](https://linuxcontainers.org/lxd/docs/master/howto/storage_volumes/#create-the-volume): `filesystem` and `block`.

When creating a volume using the [lxd_volume](https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docs/resources/volume) resource of the provider, we can specify the `type = "custom"` but we cannot choose the volume `content_type` which defaults to `filesystem`.

We should be able to specify the `content_type` to either `filesystem` or `block`.

**Comment by adamcstephens** [comment]
I tried adding this capability, but the lxd api dependency is years out of date and does not support `content_type`. 

```
lxd/resource_lxd_volume.go:103:18: invalid operation: operator + not defined on d.Get("content_type").(string) (comma, ok 
expression of type string)
lxd/resource_lxd_volume.go:109:10: volume.ContentType undefined (type api.StorageVolumesPost has no field or method Conten
tType)
lxd/resource_lxd_volume.go:109:24: undefined: contentType
```
