### ISSUE TITLE
Container thats been created with start_container as false cannot be started with true again

### ISSUE THREAD

**Issue by iamnswamyg** [terraform-lxd/terraform-provider-lxd#295]
Hi,

resource "lxd_container" "test1" {
  name      = "test1"
  image     = "ubuntu:xenial/amd64"
  profiles  = ["default"]

  start_container = false
}

When this config first applied, container is being created and set to stop but when modified to:
resource "lxd_container" "test1" {
  name      = "test1"
  image     = "ubuntu:xenial/amd64"
  profiles  = ["default"]

  start_container = true
}
it's not starting.

**Comment by adamcstephens** [comment]
`start_container` is only check on instance creation, and will not start any instance post-creation. While I investigated a solution, it feels outside the scope of the provider to manage the running state. 

I've documented this option since it was missing in the docs. #309
