### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by lukedirtwalker** [terraform-lxd/terraform-provider-lxd#299]
Hi there @adamcstephens,

Thank you for merging #293 I was wondering if there will be a release that includes that PR soon-ish?
If you have any timeline I would be very glad to hear it.

Thanks a lot.

**Comment by jtopjian** [comment]
@adamcstephens No concerns at all :)

The process I've used is to update the CHANGELOG (via the Github interface) and use that as the tagged commit. You are right in that tagging a release should kick off a build - let me know if this doesn't work.

**Comment by adamcstephens** [comment]
v1.10.0 has been released.
