### ISSUE TITLE
List instances attribute

### ISSUE THREAD

**Issue by jkermes** [terraform-lxd/terraform-provider-lxd#301]
Hello

Is there a way to retrieve a specific attribute value from all containers from a lxd remote at the same time (name for example)?

I tried the following syntax with no luck
```
output "container_names" {
  value = lxd_container.*.name
}
```

Thank you

# Edit

I found a way to do it by manually declaring a list using locals
```
locals {
  lxd_containers = [
    lxd_container.container_1,
    lxd_container.container_2
  ]
}

output "container_names" {
  value = local.lxd_containers.*.name 
}
```

**Comment by adamcstephens** [comment]
There is nothing specific about the provider here. You’ve solved this one way by using the splat operator with a list.
