### ISSUE TITLE
Rename container resource to instance

### ISSUE THREAD

**Issue by MusicDin** [terraform-lxd/terraform-provider-lxd#302]
The current `lxd_container` resource in terraform-provider-lxd represents an LXD instance rather than an actual container. This naming convention can be a bit confusing since the container can not be of type virtual machine.

To address this confusion, I propose renaming the `lxd_container` resource to `lxd_instance`. This change will better reflect its purpose and align with LXD terminology. To ensure a smooth transition and avoid breaking changes, we can deprecate the `container` resource and keep it available for a certain period of time.

I can make a PR if the maintainers agree?

**Comment by jtopjian** [comment]
@MusicDin I agree that `lxd_instance` is a better suited name. I don't think we can do a quick rename of the resource, though. It might be better to create a copy of `lxd_container` as `lxd_instance` and then mark `lxd_container` as deprecated. Thoughts?

**Comment by adamcstephens** [comment]
I agree we should probably rename it to `lxd_instance`. Copying and marking the old resource as deprecated is probably the best option. Ideally we should have a document describing how to migrate ([see this example](https://registry.terraform.io/providers/hashicorp/Azurerm/2.94.0/docs/guides/migrating-between-renamed-resources)).

sdkv2 has a section on this: https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#provider-data-source-or-resource-rename

We're definitely open to a PR @MusicDin

**Comment by MusicDin** [comment]
Hi @jtopjian and @adamcstephens

Perfect, I'll make a draft PR.
