### ISSUE TITLE
Need to update the documentation

### ISSUE THREAD

**Issue by jeet1990** [terraform-lxd/terraform-provider-lxd#307]
the lxd is now canonical lxd.  A section in the page https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docsthat is broken and pointing to LXD -->https://linuxcontainers.org/lxd/#multiple-hosts

**Comment by adamcstephens** [comment]
Links were updated in #303. I'll cut a new release once a couple of the in flight PRs are merged, which should then update the registry links.

**Comment by adamcstephens** [comment]
Most of the links are updated, but I still see a few that were missed. I'll leave this open until I can confirm all are fixed.

**Comment by adamcstephens** [comment]
Everything should be updated as of v1.10.2. Please let me know if you find any more outdated links. Thanks!
