### ISSUE TITLE
Cannot use "file {" blocks on "lxd_container" of type "virtual-machine"

### ISSUE THREAD

**Issue by tarruda** [terraform-lxd/terraform-provider-lxd#315]
I'm trying to use `file` to install a script on a new virtual machine:

```terraform
resource "lxd_container" "v1" {
  name = "v1"
  type = "virtual-machine"
  image = "images:ubuntu/22.04"
  profiles = ["default"]

  file {
    source = "scripts/docker-setup.sh"
    target_file = "/scripts/docker-setup.sh"
    uid = 0
    gid = 0
    mode = "700"
    create_directories = true
  }
}
```

When I run `terraform apply`, the following is output:

```
lxd_container.v1: Creating...
╷
│ Error: Could not upload file /scripts/docker-setup.sh: Instance not found
│
│   with lxd_container.v1,
│   on main.tf line 47, in resource "lxd_container" "v1":
│   47: resource "lxd_container" "v1" {

```
It works correctly if I comment `type = "virtual-machine"` from the container resource

**Comment by adamcstephens** [comment]
Are there any relevant server logs? Are you able to upload a file manually?

**Comment by tarruda** [comment]
I'm able to upload using the `lxc file push` command, but note that `lxc file push/pull` only works when/if the LXD agent is running in the VM. With containers is different, since LXD daemon can probably just copy the file into the rootfs.

I suspect the issue might be the delay it takes to fully boot the VM and get the agent running.

**Comment by adamcstephens** [comment]
Have you tried using `lxd_instance_file` instead?

**Comment by tarruda** [comment]
I'm new to terraform and after opening this issue I learned about the "depends_on" which could be combined with "lxd_instance_file"  to achieve the same effect.

**Comment by adamcstephens** [comment]
Sorry I didn't mention it earlier. I was looking at your fix PR and it reminded me that the other resource probably handles this already. Glad you got it working!
