### ISSUE TITLE
Support for user unix socket

### ISSUE THREAD

**Issue by invizus** [terraform-lxd/terraform-provider-lxd#320]
Please add support for user unix sockets for multi-user setup

https://discourse.ubuntu.com/t/easy-multi-user-lxd-setup/26215

`/var/snap/lxd/common/lxd-user/unix.socket`

**Comment by simondeziel** [comment]
@MusicDin I /think/ that'd be an easy one since you've already added the code to use the regular/system-wide unix socket?

**Comment by MusicDin** [comment]
I'll take a look at this one.

**Comment by simondeziel** [comment]
@invizus we were discussing about that with @MusicDin and were wondering what use case you had in mind? The things you can do with `lxd-user` access is rather limited to essentially just deal with instances.

**Comment by invizus** [comment]
@simondeziel That's right. My idea was to setup self-service LXD server for my developers. However during such long project I discovered a lot of difficulties that did not work out in the end. So right now this is no longer important for me. If lxd-user socker support is there then I might consider using it again.

My problems were these:
- when new user logs in for the first time, I have to configure their profile with "cloud-init" data and other settings like using lxdbr0.
- creating containers became easier now that cloud-init is read from the profile, but that cloud-init is shared for all instances in that profile. otherwise I would have provided a terraform template for users which they could copy/paste and use whichever cloud-init config they want. however, for my use case they only need one.

So I solved issues somehow myself, with a lot of manual work for now. Since then this project of mine is not a high priority anymore.

But thank you for the consideration and if you implement this request, I might use it.

Otherwise I think no user profiles + gitops is something to consider, or use python library client.

**Comment by MusicDin** [comment]
Hi @invizus,

we have decided to omit checking for lxd user socket by default, but it should be possible to define your own remote that uses `lxd-user/unix.socket`.

An example usage:
```hcl
provider "lxd" {
  lxd_remote {
    name     = "lxd-users"
    scheme   = "unix"
    address  = "/var/snap/lxd/common/lxd-user/unix.socket"
    default  = true
  }
}

resource "lxd_instance" "instance" {
  remote  = "lxd-users"
  project = "user-1001"

  name      = "tf-c1"
  image     = "images:alpine/3.16"
  ephemeral = false
}
```

This is currenlty available on the main branch and will be included in the next release.
