### ISSUE TITLE
Project Creation does not allow Remote

### ISSUE THREAD

**Issue by eminentv** [terraform-lxd/terraform-provider-lxd#322]
When using resource lxd_project function, for remote value, it says it is not an options.  If you need more information, let me know this is my first time using Terraform.

For example
`resource "lxd_project" "project-lxd-dev" {
    remote = "lxd-1"
    name    = "dev"
    description = "Terraform Dev Environment"
    config = {
        "features.storage.volumes" = false
        "features.nets" = false
        "features.profiles" = true
        "features.storage.volumes" = true
    }
}`

**Comment by adamcstephens** [comment]
You are correct that `lxd_project` is missing the necessary `remote` attribute.

**Comment by eminentv** [comment]
Thank you.  I am going to take a stab at trying to get add it, just started Terraform 3 days ago.

**Comment by adamcstephens** [comment]
There should be some good prior art in the other modules. Let me know if you have any questions.
