### ISSUE TITLE
Drop support for LXD versions lower then `3.0`

### ISSUE THREAD

**Issue by MusicDin** [terraform-lxd/terraform-provider-lxd#333]
I've been discussing with @simondeziel and we thought that it could be beneficial if we define a set of supported LXD versions. 

Considering LXD `3.x` has recently reached end-of-life, it seems practical to no longer support version `2.x`. By focusing on the three most recent LXD versions, we can remove the long time deprecated code, while still providing users a reasonable window for upgrades. 

Also, if someone's using the oldest version supported by the provider (for example `3.x`), we could issue a Terraform warning. This would inform the users that their current version is nearing deprecation, ensuring they aren't caught off-guard by future updates.

Any thoughts or suggestions?

**Comment by adamcstephens** [comment]
It makes sense to me to only support what upstream supports. We'll want to expand the Actions tests to add 4.0. I would lean toward having a hard failure on unsupported versions, but could be convinced to make it a warning instead. They can always not upgrade to the most recent provider version.

**Comment by MusicDin** [comment]
We thought about having a warning only for the oldest supported version, other versions (lower then the oldest supported) would have a hard failure. But we could also focus only on the active versions and just set a hard failure for others.

@simondeziel What do you think?

**Comment by simondeziel** [comment]
I like the pragmatic view of those needing to work with EOL LXD releases can use an old provider.
