### ISSUE TITLE
Can't get lxd_remotes to work

### ISSUE THREAD

**Issue by snesbittsea** [terraform-lxd/terraform-provider-lxd#336]
Despite a lot of effort, I have been unable to get lxd_remotes to work.

Basic setup is a Terraform server with LXD running. What I want to do is have Terraform create a container on remotre LXD system.

Following is my TF file:

```terraform {
  required_providers {
    lxd = {
      source  = "terraform-lxd/lxd"
      version = "~> 1.10"
    }
  }
}

provider "lxd" {
  accept_remote_certificate    = true
  generate_client_certificates = true
  lxd_remote {
        address = "xxx.xxx.xxx.xxx"
         name     = "test"
          password = "xxxx"
  }
}

resource "lxd_container" "tf_test01" {
  remote = "test"
  name     = "tf-test01"
  image    = "local:awt-bootstrap_ubuntu_jammy"
  profiles = ["default"]
  type     = "container"
}```

Operation will eventually timeout with a series of Failed To Connect errors to https://<interface ip4>:443/1.0 , one per network interface on the Terraform host. Error is failed to connect with i/o timeout.

The command:
` ``lxc launch local:awt_bootstrap_ubuntu_jammy test:mytest````
 works without problem.

```curl https://xxx.xxx.xxx.xxxx:443/1.0` ``
fails with a self-signed certificate error.

Any insight would be much appreciated.

**Comment by MusicDin** [comment]
Hi @snesbittsea.

## 1. Configure LXD

To be able to connect to the remote LXD server, you first have to expose the server.
You can do this by setting `core.https_address` in the LXD's configuration:
```sh
lxc config set core.https_address <ip>:<port>
```

For example, to expose the LXD server on port `8443`, run the following command:
```sh
lxc config set core.https_address :8443
```

You can also expose LXD server only on a specific IP address:
```sh
lxc config set core.https_address 10.48.38.128:8443
```

## 2. Verify connection

Now, check whether you can reach the remote server. When using `curl` set the `--insecure` (or shorter `-k`) flag, to accept self-signed certificates.
``` sh
curl --insecure https://<remote-ip>:8443
```

Output should look something like this:
```json
{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "operation": "",
  "error_code": 0,
  "error": "",
  "metadata": [
    "/1.0"
  ]
}
```

## 3. Configure Terraform provider

Finally, configure the Terraform provider:

```hcl
provider "lxd" {
  accept_remote_certificate = true

  lxd_remote {
    name    = "test"
    address = "10.48.38.128"   # IP address of my remote LXD server running within the VM.
    port    = "8443"           # Port on which the remote LXD server is exposed.
    scheme  = "https"          # Use http instead of unix socket.
  }
}

resource "lxd_container" "tf_test01" {
  remote   = "test"
  name     = "tf-test01"
  image    = "images:ubuntu/22.04/cloud"
  profiles = ["default"]
  type     = "container"
}
```

---

Hope this helps.

**Comment by adamcstephens** [comment]
@snesbittsea Any feedback? Did this help get you going?

**Comment by MusicDin** [comment]
I'll close this issue since it seems to be stale for quite some time. However, feel free to reopen it (or open a new one) if the above step did not solve the issue.

**Comment by HarimbolaSantatra** [comment]
I did [all the steps](https://github.com/terraform-lxd/terraform-provider-lxd/issues/336#issuecomment-1680360589) indicated by @MusicDin but mine throw the following error:
```
Unable to create server client for remote "remote_name": Unable to authenticate with remote server: not authorized
```
I exposed the server and generated a client certificate as mentioned [in the documentation](https://documentation.ubuntu.com/lxd/en/latest/howto/server_expose/). `lxc remote list` successfully shows the remote I added and curl yield
```
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0"]}
```

**Comment by MusicDin** [comment]
### Terraform remote

The trust password is documented in the [Remote API authentication - adding client certificates using a trust password](https://documentation.ubuntu.com/lxd/en/stable-5.21/authentication/#adding-client-certificates-using-a-trust-password). Note that this link is for the LXD version `5.21` (instead of `latest`), as trust password will be removed in the upcoming LXD version.

To set the trust password in LXD:
```
lxc config set core.https_address=:8443
lxc config set core.trust_password=test123
```

```hcl
provider "lxd" {
  accept_remote_certificate = true

  lxd_remote {
    name    = "test"
    address = "localhost"
    port    = "8443"
    scheme  = "https"
    password = "test123"
  }
}

# Instance for demonstration. It uses remote "test".
resource "lxd_instance" "self" {
  name   = "self"
  image  = "images:alpine/edge"
  remote = "test"
}
```

Note that when the above plan is applied `lxc remote ls` will not show the remote `test`. This remote is available only within a terraform.

---

### lxc remote

Existing remotes that have been added in `lxc` can be used in terraform directly, but only if terraform provider is running on the same host where the remote is added to the `lxc`. This is because `lxc remote` is a *local* concept and is not stored on the LXD server.

```sh
$ lxc remote add test2 localhost:8443 --password test123
Certificate fingerprint: 74305c74c383b01d883741dff6b8bc0d9b0f9afcb9cf70ebbdd7d8606e73674c
ok (y/n/[fingerprint])? y

$ lxc remote ls
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+
|         NAME         |                        URL                        |   PROTOCOL    |  AUTH TYPE  | PUBLIC | STATIC | GLOBAL |
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+
| local (current)      | unix://                                           | lxd           | file access | NO     | YES    | NO     |
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+
| test2                | https://localhost:8443                            | lxd           | tls         | NO     | NO     | NO     |
+----------------------+---------------------------------------------------+---------------+-------------+--------+--------+--------+

# Locally added remotes can be seen in config.yml
$ cat ~/snap/lxd/common/config/config.yml 
default-remote: local
remotes:
  local:
    addr: unix://
    public: false
  test2:
    addr: https://localhost:8443
    auth_type: tls
    project: default
    protocol: lxd
    public: false
aliases: {}
```

```hcl
provider "lxd" {
  accept_remote_certificate = true
}

# Instance for demonstration. It uses remote "test2".
resource "lxd_instance" "self" {
  name   = "self"
  image  = "images:alpine/edge"
  remote = "test2"
}
```

---

### trust tokens

Support for trust tokens has been added to the LXD Terraform provider, but will be available in next release `2.2.0`.

**Comment by HarimbolaSantatra** [comment]
Thank you! this solved the issue for me.
Nonetheless, using `lxd_remote` throws an error on the latest provider:
```
│ Error: Unsupported block type
│
│   on main.tf line 13, in provider "lxd":
│   13:   lxd_remote {
│
│ Blocks of type "lxd_remote" are not expected here.
```

The doc uses `remote` block instead of `lxc_remote`.

It would be nice to have these snippets with the lxd config in the documentation.
Thanks !

**Comment by simondeziel** [comment]
> Thank you! this solved the issue for me. Nonetheless, using `lxd_remote` throws an error on the latest provider:
> 
> ```
> │ Error: Unsupported block type
> │
> │   on main.tf line 13, in provider "lxd":
> │   13:   lxd_remote {
> │
> │ Blocks of type "lxd_remote" are not expected here.
> ```

Right, that's probably because the snippet was provided before the version 2.0 where the rename from [`lxd_remote` to `remote`](https://github.com/terraform-lxd/terraform-provider-lxd/blob/main/docs/guides/migration_2.0.md#renamed-attributes-and-resources) occurred.

> The doc uses `remote` block instead of `lxc_remote`.

`s/lxc/lxd/` ;)

> It would be nice to have these snippets with the lxd config in the documentation. Thanks !

I just checked and there are no `lxd_remote` nor `lxc_remote` left in the repo, except for the migration guide to 2.0 as it provides the old name (`lxd_remote`).

If I missed some occurrence, please let me know! Thanks
