### ISSUE TITLE
Provider's logo

### ISSUE THREAD

**Issue by MusicDin** [terraform-lxd/terraform-provider-lxd#344]
Hi, 

I'm just wondering whether we have any logo to set for the terraform-lxd-provider?

Otherwise, we could use the one from LXD? Logos can be found here: https://design.ubuntu.com/resources

Any thoughts @terraform-lxd/maintainers?

**Comment by adamcstephens** [comment]
Is the logo copyrighted or trademarked by Canonical, or is it public domain?

**Comment by MusicDin** [comment]
I've inquired internally and can confirm that it is a trademark of Canonical.

**Comment by adamcstephens** [comment]
This really brings up a bigger discussion as `LXD` is also trademarked by Canonical and I suspect this project has never been given explicit permission to use the brand. https://ubuntu.com/legal/intellectual-property-policy suggests to me that this permission is required, and that once granted it could be revoked or the project would need to be transferred to Canonical.

Giving the provider a different name would be awful for discoverability.

I'm not sure the best path forward, and have concerns about doubling down on using the trademarks by adding the logo. 

Do we want to ask for permission?
Do we want to rename?
Does Canonical intend to support this provider themselves?

**Comment by simondeziel** [comment]
Adam, thank for asking those important questions. Just so you know, we've reached out to the legal team who was too busy to look into this immediately but confirmed their intention to address your questions.

**Comment by MusicDin** [comment]
Hello, using LXD logo and name in the context of Terraform provider is perfectly fine. There is no concern, since the provider clearly relies on the original LXD.

**Comment by adamcstephens** [comment]
Updated the github organization icon, which feeds both the repo and terraform registry. This appears to be done.
