### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by jthing** [terraform-lxd/terraform-provider-lxd#353]
Running 'terraform plan' I get:

Terraform v1.5.7
on linux_amd64
Initializing plugins and modules...
╷
│ Error: Get "http://unix.socket/1.0": dial unix /var/snap/lxd/common/lxd/unix.socket: connect: no such file or directory
│ 
│   with provider["registry.terraform.io/terraform-lxd/lxd"],
│   on main.tf line 19, in provider "lxd":
│   19: provider "lxd" {
│ 
╵
Operation failed: failed running terraform plan (exit 1)

$ ls -l /var/snap/lxd/common/lxd/unix.socket
srw-rw---- 1 root lxd 0 Sep 15 15:41 /var/snap/lxd/common/lxd/unix.socket

$ groups
john adm cdrom sudo dip www-data plugdev lxd

So not only does the socket exist but is is read/writable.

$ curl --unix-socket /var/lib/lxd/unix.socket lxd/1.0 | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11196    0 11196    0     0  7694k      0 --:--:-- --:--:-- --:--:-- 10.6M
{
  "type": "sync",
  "status": "Success",
...

Why is it not working?

**Comment by MusicDin** [comment]
Have you installed LXD using snap?

**Comment by jthing** [comment]
yes

**Comment by MusicDin** [comment]
Is this the only installed LXD package? 

Because the provider is trying to use `/var/snap/lxd/common/lxd/unix.socket`, but the below *succes output* is from the `/var/lib/lxd/unix.socket`.

**Comment by jthing** [comment]
Must have cut and pasted wrong..

curl --unix-socket /var/lib/lxd/unix.socket lxd/1.0 | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to lxd port 80 after 0 ms: Couldn't connect to server

the output is from 
curl --unix-socket /var/snap/lxd/common/lxd/unix.socket lxd/1.0 | jq.

**Comment by simondeziel** [comment]
Could you share the output of the following commands please:

```
snap list lxd
namei -l /var/snap/lxd/common/lxd/unix.socket
lxc info
```

**Comment by adamcstephens** [comment]
I'm going to close this, but re-open as needed. We're happy to continue troubleshooting if you can provide the requested information.
