### ISSUE TITLE
deprecate remaining container attributes

### ISSUE THREAD

**Issue by adamcstephens** [terraform-lxd/terraform-provider-lxd#380]
`lxd_publish_image` and `lxd_snapshot` resources still use the legacy names `container` and `container_name`

These attributes need to be deprecated in favor of `instance` attributes. 

This work may want to wait on #381

**Comment by MusicDin** [comment]
I'm migrating to new SDK and I have reached those resources. Should it be `instance` or `instance_name` (as in [instance_file](https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docs/resources/instance_file))?

I'm happy either way, as long as it is consistent.

**Comment by adamcstephens** [comment]
I agree that we should be consistent. I think maybe `instance_name` makes sense since we're specifically wanting the _name_ attribute from the instance.

**Comment by MusicDin** [comment]
Yeah, I've just changed to `instance` everywhere hehe (can revert though). 

From my perspective `instance_name` makes more sense. As you have pointed out we are expecting its name. But then I was thinking that we also have attributes like `project`, `pool`, `network` where the name of the resource is expected, so I fixed to `instance`.

**Comment by adamcstephens** [comment]
Works for me. As you said, I mostly care about consistency here. :) Thanks for working on the plugin upgrade.
