### ISSUE TITLE
LXD has relicensed under AGPL - What will be the approach going forward?

### ISSUE THREAD

**Issue by etherealbacon** [terraform-lxd/terraform-provider-lxd#399]
LXD has relicensed to AGPL. Given that this project is depending on the go client from their repo is there an idea of whether this project will become APL or if updates will cease?

Many thanks for the efforts and work so far on this project.

**Comment by adamcstephens** [comment]
As of this point, we are using the client from just before the license change. https://github.com/terraform-lxd/terraform-provider-lxd/pull/397

**Comment by tomponline** [comment]
Hi,

There has been an update posted about this here https://discourse.ubuntu.com/t/an-update-on-the-licence-change-and-community-image-server/41549

**Comment by tomponline** [comment]
The Go SDK client is now licensed out as Apache-2.0 

https://github.com/canonical/lxd/pull/12731

**Comment by MusicDin** [comment]
@tomponline Thanks for the clarification.
