### ISSUE TITLE
Failing tests in LXD 5.0/edge

### ISSUE THREAD

**Issue by MusicDin** [terraform-lxd/terraform-provider-lxd#428]
Some tests are occasionally failing on LXD 5.0/edge and require further investigation.

Examples:
- [x] VM fails to stop in TestAccInstance_restartVirtualMachine: https://github.com/terraform-lxd/terraform-provider-lxd/actions/runs/7717387499/job/21036403945?pr=426#step:8:147
- [x] Test timeouts in TestAccCachedImage_addRemoveAlias: https://github.com/terraform-lxd/terraform-provider-lxd/actions/runs/7713360862/job/21023073291#step:8:109

**Comment by simondeziel** [comment]
>     * VM fails to stop in TestAccInstance_restartVirtualMachine: https://github.com/terraform-lxd/terraform-provider-lxd/actions/runs/7717387499/job/21036403945?pr=426#step:8:147

This was with `5.0/edge` with `lvm` and the VM failed to stop. Makes me think it could have been https://github.com/canonical/lxd/issues/12808?

**Comment by simondeziel** [comment]
> > * VM fails to stop in TestAccInstance_restartVirtualMachine: https://github.com/terraform-lxd/terraform-provider-lxd/actions/runs/7717387499/job/21036403945?pr=426#step:8:147
> 
> This was with `5.0/edge` with `lvm` and the VM failed to stop. Makes me think it could have been [canonical/lxd#12808](https://github.com/canonical/lxd/issues/12808)?

Scratch that, I came to the conclusion `lvm` was used due to https://github.com/terraform-lxd/terraform-provider-lxd/actions/runs/7717387499/job/21036403945?pr=426#step:4:29 but looking at the test case, it doesn't specify any storage driver so it probably was using `dir`.

**Comment by simondeziel** [comment]
It looks like `5.0/edge` is now green but `5.0/stable` is failing. There is a new rev coming up to `5.0/stable` so maybe that will fix it.

**Comment by MusicDin** [comment]
I'm closing this as tests seem to be stable now. The issue was that multiple tests (routines) tried to authenticate with LXD server which caused a race condition.
