### ISSUE TITLE
Replace `square/go-jose` by `go-jose/go-jose`

### ISSUE THREAD

**Issue by simondeziel** [terraform-lxd/terraform-provider-lxd#474]
Same issue as https://github.com/canonical/lxd/issues/13526 except that we don't yet depend on `github.com/go-jose/go-jose/v4` already.

Doing that transition should address https://github.com/terraform-lxd/terraform-provider-lxd/security/dependabot/35

**Comment by simondeziel** [comment]
@MusicDin it seems the `square/go-jose` dependency comes from `lxd` itself. Do you think that fixing LXD will be the only thing needed?

**Comment by MusicDin** [comment]
Yes. We use `square/go-jose` indirectly, therefore, we need to address this issue in LXD.
