### ISSUE TITLE
Provider expects LXD REST API to expose server version

### ISSUE THREAD

**Issue by gchamon** [terraform-lxd/terraform-provider-lxd#515]
Currently I am facing an issue that wasn't present in version 2.1.0, which is that it requires the
server to expose it's version through the API.

Currently I can get the version using `lxc info` with the command line:

```yaml
config:
  core.https_address: :8443
  core.https_allowed_origin: '*'
api_extensions:
- ...
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
auth_user_name: gchamon
auth_user_method: unix
environment:
  addresses:
  - ...
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  certificate_fingerprint: ...
  driver: lxc | qemu
  driver_version: 6.0.1 | 9.0.2
  instance_types:
  - container
  - virtual-machine
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 6.6.46-1-lts
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Arch Linux
  os_version: ""
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: anarchy
  server_pid: 2046
  server_version: "6.1"
  server_lts: false
  storage: dir
  storage_version: "1"
  storage_supported_drivers:
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.25(2) (2024-07-12) / 1.02.199 (2024-07-12) / 4.48.0
    remote: false
```

But the API doesn't expose that. Using `curl --insecure https://localhost:8443/1.0` I get:

```json
{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "operation": "",
  "error_code": 0,
  "error": "",
  "metadata": {
    "api_extensions": [
      "..."
    ],
    "api_status": "stable",
    "api_version": "1.0",
    "auth": "untrusted",
    "public": false,
    "auth_methods": [
      "tls"
    ]
  }
}
```

This causes terraform to panic:

```
╷
│ Error: Failed to retrieve LXD InstanceServer
│ 
│   with lxd_instance.dms_on_lxd["dms-0"],
│   on main.tf line 53, in resource "lxd_instance" "dms_on_lxd":
│   53: resource "lxd_instance" "dms_on_lxd" {
│ 
│ Unable to create server client for remote "...": Unable to parse version "": Malformed version: 
```

How should I configure my LXD servers to prepare them for the updated version 2.2.0 of this provider? I have read through the LXD documentation trying to see how I can setup the `/1.0` endpoint to expose the server version, but I can't seem to find how to configure it.

**Comment by MusicDin** [comment]
If you insecurely call the `localhost:8443/1.0` endpoint, most of the server metadata is omitted because the client is considered untrusted. You can check that the proper version is returned from the LXD using `lxc query /1.0`?

Hmm, are you by any chance using trust password for remote LXD?

**Comment by MusicDin** [comment]
I suspect the regression is coming from this change: https://github.com/terraform-lxd/terraform-provider-lxd/pull/484/commits/34e151d9440abf649817a4e2d1f0b2fce041b94d

**Comment by MusicDin** [comment]
Reproducer:

```
lxc config set core.https_address=:8443
lxc config set core.trust_password=test
```

```hcl
provider "lxd" {
  accept_remote_certificate = true
  generate_client_certificates = true

  remote {
    name     = "tf-https"
    address  = "localhost"
    scheme   = "https"
    password = "test"
  }
}

resource "lxd_profile" "profile" {
  name   = "tf-profile"
  remote = "tf-https"
}
```
```
terraform apply --auto-approve
```

Result:
```
│ Error: Failed to retrieve LXD InstanceServer
│ 
│   with lxd_profile.profile,
│   on main.tf line 21, in resource "lxd_profile" "profile":
│   21: resource "lxd_profile" "profile" {
│ 
│ Unable to create server client for remote "tf-https": Unable to parse version "": Malformed version:
```

**Comment by gchamon** [comment]
@MusicDin yes! I am trying with the trust password. Need to use it before I shift to tokens, otherwise our solution would stop working until we update the configuration files with tokens

**Comment by gchamon** [comment]
> If you insecurely call the `localhost:8443/1.0` endpoint, most of the server metadata is omitted because the client is considered untrusted. You can check that the proper version is returned from the LXD using `lxc query /1.0`.
> 
> This seems more like the provider is trying to fetch the version from remote LXD server before it is trusted. Are you by any chance using the trust password for remote LXD?

this is because password auth has been removed I believed from version 6.0 onwards, so the provider correctly tries to infer whether the target API is capable of authenticating with the password using the server version. However the version isn't available until a successful authentication, creating a kind of a deadlock.

Maybe the correct approach would be to just use whatever the user configures the provider to use? If the provider can't authenticate using the API it's a configuration issue. As long as the error is clear, maybe checking the version of the server is redundant.

**Comment by MusicDin** [comment]
And thank you very much for reporting the issue :)

**Comment by gchamon** [comment]
@MusicDin thanks for the swift response!

**Comment by gchamon** [comment]
@MusicDin with token it works as expected
