### ISSUE TITLE
Vanilla LXD standalone server cannot be provisioned, accept_remote_certificate=true has no effect

### ISSUE THREAD

**Issue by Teebor-Choka** [terraform-lxd/terraform-provider-lxd#532]
The vanilla standalone LXD with some minor configs cannot be provisioned using the provider, encountering this error:

```
│ Error: Failed to retrieve LXD InstanceServer
│
│   with lxd_instance.hoprd-rotsee,
│   on main.tf line 37, in resource "lxd_instance" "<redacted>":
│   37: resource "lxd_instance" "<redacted>" {
│
│ Get "https://192.168.0.55:8443/1.0": tls: failed to verify certificate: x509: certificate is
│ valid for 127.0.0.1, ::1, not 192.168.0.55
```

The provider configuration is:
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.3.0"
    }
  }
}

provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true

  remote {
    name    = "<redacted>"
    address = "https://192.168.0.55:8443"
    password = "<redacted>"
  }
}
```

The LXD standalone server has the password configured and uses a default generated `server.crt`. I remember this working a long time ago when I used this provider in the past, but this does not seem to be the case anymore.

Any idea, what I should fix? My feeling is that by setting the `accept_remote_certificate    = true` the certificate should not be checked at all.

Terraform running in platform: MacOS
terraform 1.5.7

**Comment by Teebor-Choka** [comment]
@MusicDin @simondeziel

**Comment by MusicDin** [comment]
Hi,

could you show the contents of the accepted remote certificate on the host where Terraform is being run (should be in `~/snap/lxd/common/config/servercerts/<remote-name>.crt`). Also, can you remove/rename the accepted certificate and try again?

The `accept_remote_certificate` does not mean that certificate is *not validated*, but rather that whatever certificate the remote server presents us, we accept it unconditionally (without checking its fingerprint). However, once the remote certificate is accepted, this has no effect.

**Comment by Teebor-Choka** [comment]
Do you want the standalone LXD instance's cert on the virtual linux machine, correct?

**Comment by MusicDin** [comment]
I would suggest comparing the actual remote certificate to the accepted one. Have you tried removing the currently accepted certificate (on the host/vm where you are running `terraform apply`)?

**Comment by MusicDin** [comment]
In addition, is there any proxy in between that could mess with the cert on a TLS layer?

And just to confirm, can you run add the remote (`lxc remote add <remote-name> https://192.168.0.55:8443`) from the host where Terraform is being run?

**Comment by Teebor-Choka** [comment]
Will test this out in 3 days.

**Comment by Teebor-Choka** [comment]
> I would suggest comparing the actual remote certificate to the accepted one. Have you tried removing the currently accepted certificate (on the host/vm where you are running `terraform apply`)?

'terraform' is ran from a brew installed terraform on MacOS.

**Comment by Teebor-Choka** [comment]
I retested and the same error persists.

> And just to confirm, can you run add the remote (lxc remote add <remote-name> https://192.168.0.55:8443) from the host where Terraform is being run?

I cannot run lxc command on the terraform host, it is a MacOS machine.

> could you show the contents of the accepted remote certificate on the host where Terraform is being run (should be in ~/snap/lxd/common/config/servercerts/<remote-name>.crt). Also, can you remove/rename the accepted certificate and try again?

No such directory exists, terraform command running machine is not Linux and does not have that dir.

**Comment by MusicDin** [comment]
If lxc is not installed installed via snap, then it should be in `~/.config` dir I think (need to double check). 

Why can't you test on macos? LXD does not work on macos, but lxc should work just fine.

**Comment by Teebor-Choka** [comment]
> If lxc is not installed via snap, then it should be in `~/.config` dir I think (need to double check).
> 
> Why can't you test on macos? LXD does not work on macos, but lxc should work just fine.

Let's backtrack. I have a `terraform` on MacOS installed with `brew` applying the configuration. It uses this extension to connect to the remote instance LXC+LXD running on a remote Linux server in the local network. What should I fetch from where?

**Comment by MusicDin** [comment]
Here, I've tried it on macos using terraform installed via brew.

```sh
$ brew tap hashicorp/tap
$ brew install hashicorp/tap/terraform

$ which terraform
/opt/homebrew/bin/terraform

$ terraform --version
Terraform v1.9.7
on darwin_arm64
```

Here is the configuration. I'm using trust token instead of password, and the `config_dir` is set to `./config` just for test purposes (If not set, you can find them in `~/.config/lxc`). Once the Terraform is run, it will generate a client certificate if missing (in `./config/client.{crt,key}`), and accept the the remote LXD certificate (in `./config/servercerts/my-remote.crt`).
```hcl
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.4.0"
    }
  }
}

provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true
  config_dir                   = "./config"

  remote {
    name    = "my-remote"
    address = "https://10.2.0.42:8443"
    token   = "<token>" # Generate on remote using "lxc trust config add --name my-remote --quiet"
    default = true
  }
}

resource "lxd_instance" "inst" {
  name      =  "c1"
  image     = "images:alpine/edge"
  ephemeral = true
}
```

Applying the configuration:
```sh
$ terraform init
$ terraform apply --auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # lxd_instance.inst will be created
  + resource "lxd_instance" "inst" {
      + config           = {}
      + description      = ""
      + ephemeral        = true
      + image            = "images:alpine/edge"
      + interfaces       = (known after apply)
      + ipv4_address     = (known after apply)
      + ipv6_address     = (known after apply)
      + limits           = {}
      + mac_address      = (known after apply)
      + name             = "c1"
      + profiles         = [
          + "default",
        ]
      + running          = true
      + status           = (known after apply)
      + target           = (known after apply)
      + type             = "container"
      + wait_for_network = true
    }

Plan: 1 to add, 0 to change, 0 to destroy.
lxd_instance.inst: Creating...
lxd_instance.inst: Still creating... [10s elapsed]
lxd_instance.inst: Still creating... [20s elapsed]
lxd_instance.inst: Creation complete after 28s [name=c1]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Here are the resulting certificates.
```sh
$ ls ./config 
client.crt  client.key  servercerts

$ ls ./config/servercerts 
my-remote.crt
```

I was asking if you can try adding the remote using `lxc remote add` to confirm whether the same issue issue applies using `lxc` or just using Terraform. The `lxc` can also be installed using brew (`brew install lxc`).

**Comment by Teebor-Choka** [comment]
Now I know what to look for. Looking at the locally stored certificate, it belonged to a different server. Upon removing it, it was again possible to deploy using the lxd provider. Do you think the certificate should be pruned after usage though? Since it was introduced automatically, if the server setup changes/certificate is changed (e.g. KVM setup), should it also be removed automatically, when the accept remote certificate is `true`?

**Comment by MusicDin** [comment]
Nice, I'm glad you got it solved.

Setting `accept_remote_certificate` to `true` just means that the remote certificate should be *blindly* (whatever certificate is presented to the client) accepted **if missing**. However, if a remote from lxc's `config.yaml` is used, the remote certificate is most likely already there. 

While we could detect whether the Terraform has accepted the certificate (and later remove it on destroy), the issue arises if multiple Terraform providers rely on the same remote. This may cause issues when running multiple configurations that rely on the same remote (especially in parallel) - where one should not remove the certificate if other is using it, but how do we detect whether there are other configurations/projects that need it?

If the remote environment is expected to be ephemeral and does continuously change, you can remove the accepted remote certificates either outside of Terraform's scope or using [terraform_data](https://developer.hashicorp.com/terraform/language/resources/terraform-data) with [local-exec](https://developer.hashicorp.com/terraform/language/resources/provisioners/local-exec). Using a unique remote name for such environment may be helpful.

**Comment by Teebor-Choka** [comment]
Thanks you. I'm using the provider inside a sandboxed terraform instance inside the crossplane.
