### ISSUE TITLE
Provider says multiple default remotes configured when only one is

### ISSUE THREAD

**Issue by llama233** [terraform-lxd/terraform-provider-lxd#533]
I edit my Terraform code on my laptop with the provider set up using a remote to access my LXD cluster:

```
provider "lxd" {
  generate_client_certificates = true
  accept_remote_certificate    = true

  remote {
    name     = "beetle"
    address  = "https://192.168.3.21:8443"
    token    = "token"
    default  = true
  }
}
```

If I try and run terraform plan I get this error:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Failed initialize LXD provider
│
│   with provider["registry.terraform.io/terraform-lxd/lxd"],
│   on provider.tf line 14, in provider "lxd":
│   14: provider "lxd" {
│
│ Multiple remotes are configured as default: [beetle]
```

I can work around this by not setting a default, then specifying a remote on each resource, and that works correctly, but it would be nice not to have to do this with each resource.

Cheers,
Andrew

**Comment by MusicDin** [comment]
Thanks for reporting this. Can reproduce the issue - this is regression in 2.3.0
