### ISSUE TITLE
Fails if remote address contains a subdirectory

### ISSUE THREAD

**Issue by tam1192** [terraform-lxd/terraform-provider-lxd#539]
# summary
The following settings will fail.
```tf
 remote {
    name    = "ubuntu-ex"
    protocol = "simplestreams"
    address = "https://example.com/ubuntu-cloud-images/releases/"
  }
```
※Domain section is hidden.

```
resource "lxd_cached_image" "image" {
    source_remote   = "ubuntu-ex"
    source_image    = "24.04"
    type            = "container"
}
```

Errors are as follows
```
│ Failed getting image: Failed parsing stream: Unable to fetch
│ https://example.com/ubuntu-cloud-images/releases/:443/streams/v1/index.json: 404 Not Found
```

https://example.com/ubuntu-cloud-images/releases/streams/v1/index.json
has been confirmed to exist.

# What you need to fix
I want the port number to come to the proper location when making http requests.

https://example.com/ubuntu-cloud-images/releases/:443/streams/v1/index.json
↓
https://example.com:443/ubuntu-cloud-images/releases/streams/v1/index.json

**Comment by tam1192** [comment]
You forgot to include the version.
```
└─$ terraform --version
Terraform v1.6.3-dev
on linux_amd64
+ provider registry.terraform.io/ansible/ansible v1.3.0
+ provider registry.terraform.io/terraform-lxd/lxd v2.4.0

Your version of Terraform is out of date! The latest version
is 1.9.8. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by MusicDin** [comment]
Hi, yes the port is appended if missing, but it seems to be placed at the end of the URL instead of the end of the domain name. Thanks for reporting this.

As a temporary solution, could you try manually adding the port (`:443`) after the domain to prevent provider from adding it automatically?

Something like this:
```hcl
remote {
  name     = "ubuntu-ex"
  protocol = "simplestreams"
  address  = "https://example.com:443/ubuntu-cloud-images/releases/"
  #                              ^^^^
}
```

**Comment by tam1192** [comment]
Thank you very much for your prompt reply.　I added it and now I can communicate with no problem.

I will use this solution until the bug is resolved.

Thank you very much.
