### ISSUE TITLE
how to perform "remote-exec", but inside the LXD

### ISSUE THREAD

**Issue by shantanugadgil** [terraform-lxd/terraform-provider-lxd#54]
Terraform version: Terraform v0.9.6
terraform-provider-lxd: 0.9.5 beta1

As part of the LXD creation, I push some config files and a service startup script (upstart)
These cannot be baked into the LXD image.

It would be quite useful if I could target command execution directly inside the LXD container.

For now, I am making do with a "remote-exec" on the LXD server and do:
```lxd exec mylxd1 -- telinit 2```  (to make the upstart script start)

Regards,
Shantanu

**Comment by sl1pm4t** [comment]
@jtopjian and I have discussed this a little in the past.
To get the native `remote-exec` working via the LXD websocket exec channel we'd need to add some code to Terraform core (which that project may or may not be willing to accept, but is extremely unlikely while this provider is a separate project).

@jtopjian had floated the idea of a `lxd_remote_exec` pseudo resource as a workaround in the meantime, however I believe he didn't put in any effort yet. This is because the plan is to eventually contribute this provider code to the main Terraform project and then tackle websocket exec channel.

**Comment by shantanugadgil** [comment]
+1 for `lxd_remote_exec` from side.
I already have a setup where I could test this.

**Comment by yobert** [comment]
I work around this by doing something like
`provisioner "local-exec" {
  command = <<EXEC
lxc exec ${var.instance_name} -- bash -xe -c '
echo "this runs inside the container!"
'
EXEC
}`

**Comment by yahyakkhalid** [comment]
For anyone who uses VPN on the LXD server, and wants to be able to connect remotely to the created containers using Terraform, you can simply use this resource to transfer the SSH public keys to the container.

resource "lxd_container_file" "authorized-keys" {
  container_name     = "${lxd_container.CONTAINER-NAME.name}"
  target_file               = "/root/.ssh/authorized_keys"
  source                    = "/path/to/public-keys"
  append                   = true
  create_directories   = true
}

You can then connect to the container using:
ssh root@CONTAINER-IP

**Comment by dorkamotorka** [comment]
@jtopjian I know this issue is old, but still, I see great benefit in adding a `lxd_remote_exec` resource, and on first look, it doesn't seem a big issue, since this is something that LXD API supports. Have you tried it before? What stooped you from doing it?

**Comment by tregubovav-dev** [comment]
Recently LXD introduced new attributes in **/1.0/containers/<name>/exec** API call which allows to exec remote command without using websockets 
Source: https://documentation.ubuntu.com/lxd/en/latest/api-extensions/#container-exec-recording
`container_exec_recording
Introduces a new Boolean record-output, parameter to /1.0/containers/<name>/exec which when set to true and combined with with wait-for-websocket set to false, will record stdout and stderr to disk and make them available through the logs interface.

The URL to the recorded output is included in the operation metadata once the command is done running.

That output will expire similarly to other log files, typically after 48 hours.`
