### ISSUE TITLE
`Failed to marshal state to json: unsupported attribute "id"` when upgrading from 1.x to 2.x

### ISSUE THREAD

**Issue by aanderse** [terraform-lxd/terraform-provider-lxd#543]
unfortunately i have a project which i hadn't been able to upgrade my lxd terraform provider from 1.x to 2.x until now - i know this is quite late in the game... but maybe someone will be able to help me :bowing_man:

if i upgrade my lxd terraform provider from the last version in the 1.x series (1.10.14) to 2.0.0 i suddenly get the following error when i run `terraform plan`:

`Failed to marshal state to json: unsupported attribute "id"`

in the past i did this upgrade on some infrastructure that did not define an `lxd_project` and it worked... the current infrastructure i'm working on defines an `lxd_project` and some `lxd_instances`... maybe `lxd_project` is the issue?

---

any advice, etc... would be **greatly** appreciated, thank you

**Comment by MusicDin** [comment]
Hi, is could you show the source (HCL) of the project?

Also, this guide may help: https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docs/guides/migration_2.0

**Comment by aanderse** [comment]
here are some relevant snippets of my terraform configuration, which uses the `json` variant as opposed to `hcl`:

```
{
  "provider": [
  {
    "lxd": {
      "accept_remote_certificate": true,
      "config_dir": "../infra/config",
      "generate_client_certificates": true,
      "lxd_remote": {
        "address": "${module.lxd_tunnel.host}",
        "default": true,
        "name": "default",
        "password": "${data.sops_file.alpha0-hetz.data[\"lxd.trust\"]}",
        "port": "${module.lxd_tunnel.port}",
        "scheme": "https"
      }
    }
  },
  ],
  "resource": {
  "lxd_project": {
    "project": {
      "config": {
        "features.images": false,
        "features.profiles": false,
        "features.storage.volumes": false
      },
      "name": "foo"
    },
    "lxd_instance": {
    "dash": {
      "config": {
        "boot.autostart": true
      },
      "image": "nixos",
      "name": "dash",
      "profiles": [
        "default"
      ],
      "project": "${lxd_project.project.name}",
      "target": "668-fsn1-dc20-hetz"
    },
    }
  },
  }
}
```

**Comment by aanderse** [comment]
one thing i noticed when i pulled down the terraform state (via `terraform state pull > data.tfstate`) and inspected it manually...

```
    {
      "mode": "managed",
      "type": "lxd_project",
      "name": "project",
      "provider": "provider[\"registry.terraform.io/terraform-lxd/lxd\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "config": {
              "features.images": "false",
              "features.profiles": "false",
              "features.storage.volumes": "false"
            },
            "description": "",
            "id": "foo",
            "name": "foo",
            "target": null
          },
        }
      ]
    },
```

if i create a `lxd_project` in a completely different terraform project using the 2.x provider things look a bit different... specifically, no `id` attribute :thinking:

```
    {
      "mode": "managed",
      "type": "lxd_project",
      "name": "foo-test-project",
      "provider": "provider[\"registry.terraform.io/terraform-lxd/lxd\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "config": {
              "features.images": "false",
              "features.profiles": "false",
              "features.storage.volumes": "false"
            },
            "description": "",
            "name": "foo-test-project",
            "remote": null
          },
        }
      ]
    },
```

:man_shrugging:

**Comment by aanderse** [comment]
i tried a few things like that without much success

in the end i opted to do a manual `terraform state rm` for _all_ my `lxd` objects (not just `lxd_project` as i initially suspected) and then add them all back... i didn't want to spend any more time digging into it

thanks again @MusicDin for your efforts :bowing_man:
