### ISSUE TITLE
lxd_instance reporting "local" ipv6 address as "global"

### ISSUE THREAD

**Issue by aanderse** [terraform-lxd/terraform-provider-lxd#547]
according to [wikipedia](https://en.wikipedia.org/wiki/Unique_local_address)

> A unique local address (ULA) is an Internet Protocol version 6 (IPv6) address in the address range fc00::/7

if i inspect the ip address structure that `terraform` has of my `test` container i see multiple addresses, including the following:

`resources.lxd_instance.test.interfaces.eth0.ips`:
```
[
  { address = "fd19:cafe:637:0:216:3eff:fe76:53f2"; family = "inet6"; scope = "global"; }
]
```

i believe that `scope` should be `"local"` here

**Comment by MusicDin** [comment]
The provided address is indeed a unique local address that is part of the `fc00::/7` range. Similar to IPv4 private addresses (such as `192.168.0.0/16`), they are not routable on the public internet.

The scope value of *global* might appear misleading but is accurate in this context, where `global` refers to addresses that are valid beyond the local `link` (routable across subnets or within a private network). However, this does not imply that the address is routable on the internet.

To verify the scope from within the instance itself, you can run `ip addr`. This will confirm whether the scope reported by LXD aligns with the configuration inside the instance.

Regarding `local` addresses, I think LXD considers only host addresses as `local` - addresses that are not routable outside the host itself, or simply put `127.0.0.1/8` and `::1/128` (in Linux their scope is usually marked as `host`).

**Comment by aanderse** [comment]
thanks for the explanation, that helps me :heart:
