### ISSUE TITLE
limits on profiles

### ISSUE THREAD

**Issue by jfgibbins** [terraform-lxd/terraform-provider-lxd#84]
Noticed, that though the readme states profiles accept the same configuration and device options that containers can use, it does appear that "limits" is not one of them.  Guessing just overlooked when you guys were trying to enable changing limits without recreating containers.  Just an FYI.

**Comment by sl1pm4t** [comment]
Thanks @jfgibbins. Good point.

**Comment by jfgibbins** [comment]
Anytime, just trying to help without being too much of a pain in the ass.  :)

**Comment by jtopjian** [comment]
This should now be resolved in #227.
